package BookStore;


import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.ScrollPane;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import oracle.jdbc.pool.OracleDataSource;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class VCustomer extends javax.swing.JFrame {

    public String isbn;
    public String title;
    public String author;
    public byte[] img;
    public static ImageIcon tableImg;
    public static String tableISBN;
    public static String tableTitle;
    public static String tableAuthor;
    
    public ArrayList<VCustomer> data = new ArrayList<VCustomer>();
    public VCustomer(String isbn,byte[] img,String title,String author)
    {   
        this.isbn=isbn;
        this.img=img;
        this.title=title;
        this.author=author; 
        
    }
    /**
     * Creates new form Customer
     */
    public VCustomer() {
        initComponents();
        parent.removeAll();
        parent.add(home);
        parent.repaint();
        parent.revalidate();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }
    //setters
    public void setISBN(String isbn)
    {
        this.isbn=isbn;
    }
    public void setTitle(String title)
    {
        this.title=title;
    }
    public void setAuthor(String author)
    {
        this.author=author;
    }
    public void setTitle(byte[] img)
    {
        this.img=img;
    }
    
    //getters
    public String getISBN()
    {
        return isbn;
    }
    public String getTitle()
    {
        return title;
    }
    public String getAuthor()
    {
        return author;
    }
    public byte[] getImg()
    {
        return img;
    }
    public ImageIcon gettableImg()
    {
        return tableImg;
    }
    public String gettableISBN()
    {
        return tableISBN;
    }
    public String gettableTitle()
    {
        return tableTitle;
    }
    public String gettableAuthor()
    {
        return tableAuthor;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        edit1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        home1 = new javax.swing.JButton();
        shop1 = new javax.swing.JButton();
        suggest1 = new javax.swing.JButton();
        contactus2 = new javax.swing.JButton();
        viewCart = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        parent = new javax.swing.JPanel();
        edit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        shop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        suggest = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        conntactUs = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        viewCart1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(0, 153, 153));
        menu.setLayout(new java.awt.GridLayout(11, 0));

        edit1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        edit1.setText("Edit Profile");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        menu.add(edit1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookStore/bookshelf.png"))); // NOI18N
        menu.add(jLabel3);

        home1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        home1.setText("Home");
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        menu.add(home1);

        shop1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        shop1.setText("Shop");
        shop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shop1ActionPerformed(evt);
            }
        });
        menu.add(shop1);

        suggest1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        suggest1.setText("Suggest");
        suggest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggest1ActionPerformed(evt);
            }
        });
        menu.add(suggest1);

        contactus2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        contactus2.setText("Contact Us");
        contactus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactus2ActionPerformed(evt);
            }
        });
        menu.add(contactus2);

        viewCart.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        viewCart.setText("View Cart");
        viewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartActionPerformed(evt);
            }
        });
        menu.add(viewCart);
        menu.add(jLabel26);
        menu.add(jLabel24);

        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        menu.add(jButton7);

        parent.setLayout(new java.awt.CardLayout());

        edit.setBackground(new java.awt.Color(102, 255, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel8.setText("Phone");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel9.setText("City");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel11.setText("Username");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel12.setText("Password");

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12)
                                .addGap(57, 57, 57)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editLayout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(197, 197, 197))
        );

        parent.add(edit, "card2");

        home.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookStore/mhome.png"))); // NOI18N

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 193, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 175, Short.MAX_VALUE))
        );

        parent.add(home, "card3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout shopLayout = new javax.swing.GroupLayout(shop);
        shop.setLayout(shopLayout);
        shopLayout.setHorizontalGroup(
            shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1059, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 301, Short.MAX_VALUE))
        );
        shopLayout.setVerticalGroup(
            shopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 140, Short.MAX_VALUE))
        );

        parent.add(shop, "card4");

        suggest.setBackground(new java.awt.Color(153, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Book Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Book Author");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Date");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Zilla Slab SemiBold", 1, 18)); // NOI18N
        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("(DD-MM-YYYY)");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 153));
        jLabel21.setText("Book ISBN");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BookStore/opinion.png"))); // NOI18N

        javax.swing.GroupLayout suggestLayout = new javax.swing.GroupLayout(suggest);
        suggest.setLayout(suggestLayout);
        suggestLayout.setHorizontalGroup(
            suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suggestLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suggestLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(suggestLayout.createSequentialGroup()
                        .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(suggestLayout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        suggestLayout.setVerticalGroup(
            suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suggestLayout.createSequentialGroup()
                .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suggestLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(suggestLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(suggestLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(suggestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 260, Short.MAX_VALUE))
        );

        parent.add(suggest, "card5");

        conntactUs.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Andalus", 3, 48)); // NOI18N
        jLabel14.setText("Email");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Nablus-Alnajah street");

        jLabel16.setFont(new java.awt.Font("Andalus", 3, 48)); // NOI18N
        jLabel16.setText("Phone");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("bookshop02@gmail.com");

        jLabel18.setFont(new java.awt.Font("Andalus", 3, 48)); // NOI18N
        jLabel18.setText("Adderss");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("+97256913275");

        javax.swing.GroupLayout conntactUsLayout = new javax.swing.GroupLayout(conntactUs);
        conntactUs.setLayout(conntactUsLayout);
        conntactUsLayout.setHorizontalGroup(
            conntactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conntactUsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(conntactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(conntactUsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(conntactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(519, Short.MAX_VALUE))
        );
        conntactUsLayout.setVerticalGroup(
            conntactUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conntactUsLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(conntactUsLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        parent.add(conntactUs, "card6");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Cart ID", "ISBN", "Title", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Delete Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 255, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Conform Order");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewCart1Layout = new javax.swing.GroupLayout(viewCart1);
        viewCart1.setLayout(viewCart1Layout);
        viewCart1Layout.setHorizontalGroup(
            viewCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCart1Layout.createSequentialGroup()
                .addGroup(viewCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewCart1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewCart1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        viewCart1Layout.setVerticalGroup(
            viewCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewCart1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(viewCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 193, Short.MAX_VALUE))
        );

        parent.add(viewCart1, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(460, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        parent.removeAll();
        parent.add(home);
        parent.repaint();
        parent.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_home1ActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        parent.removeAll();
        parent.add(edit);
        parent.repaint();
        parent.revalidate();  
        

// TODO add your handling code here:
    }//GEN-LAST:event_edit1ActionPerformed

    private void shop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shop1ActionPerformed
        parent.removeAll();
        parent.add(shop);
        parent.repaint();
        parent.revalidate();        // TODO add your handling code here:
        Object source = evt.getSource();
       
        if (source == shop1) {
            int flag = 0, count = 0;
            try {
                
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String user, url, Password;
                url = "jdbc:oracle:thin:@192.168.1.184:1521:XE";
                user = "C##BOOKSTORE";
                Password = "scranton";
                Connection con = DriverManager.getConnection(url, user, Password);
                con.setAutoCommit(false);

                String sql = "select isbn,title,author,book_image from books";
                Statement smt = con.createStatement();
                ResultSet rs = smt.executeQuery(sql);
                VCustomer c;
                while (rs.next()) {
                    c = new VCustomer(rs.getString("isbn"),rs.getBytes("book_image"),rs.getString("title"),rs.getString("author"));
//                    ImageIcon image = new ImageIcon(img);
//                    Image im = image.getImage();
//                    Image myimg = im.getScaledInstance(40, 40, Image.SCALE_SMOOTH);
//                    ImageIcon icon = new ImageIcon(myimg);
                    data.add(c);
                   
                }
                String[] columnName = {"ISBN","Title","Author"};
                Object[][] rows = new Object[data.size()][3];
                for(int i=0;i<data.size();i++)
                {
                    /*if(data.get(i).getImg() !=null)
                    {
                        
                        ImageIcon icon = new ImageIcon(new ImageIcon(data.get(i).getImg()).getImage().getScaledInstance(100,120,Image.SCALE_SMOOTH));
                        rows[i][0] = icon;
                    }*/
                    rows[i][0] = data.get(i).getISBN();
                    rows[i][1] = data.get(i).getTitle();
                    rows[i][2] = data.get(i).getAuthor();
                    
                }
                TheModel model = new TheModel(rows,columnName);
                jTable1.setModel(model);
                jTable1.setRowHeight(120);
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_shop1ActionPerformed

//    class myTableCellRenderer implements TableCellRenderer
//    {
//
//        public Component getTableCellRendererComponent(JTable table,Object value, boolean isSelected, boolean hasFocus,int row,int column)
//        {
//            return (Component) value;
//        }
//    }
    private void suggest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggest1ActionPerformed
        parent.removeAll();
        parent.add(suggest);
        parent.repaint();
        parent.revalidate(); // TODO add your handling code here:
    }//GEN-LAST:event_suggest1ActionPerformed

    private void viewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartActionPerformed
        parent.removeAll();
        parent.add(viewCart1);
        parent.repaint();
        parent.revalidate();        // TODO add your handling code here:
        if(evt.getSource()==viewCart)
        {
            try
            {
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                logIn l = new logIn();
                String strISBN = String.valueOf(l.getssn());
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String user,url,Password;
            url="jdbc:oracle:thin:@192.168.1.184:1521:XE";
            user="C##BOOKSTORE";
            Password="scranton";
            Connection con = DriverManager.getConnection(url,user,Password);
            con.setAutoCommit(false);
            String sql = "select * from items_cus where c_id = '"+strISBN+"'";
            Statement smt = con.createStatement();
            ResultSet rs = smt.executeQuery(sql);
            model.getDataVector().removeAllElements();
            while(rs.next())
            {
                String cID = rs.getString("c_id");
                String isbn = rs.getString("isbn");
                String title = rs.getString("title");
                String quan = rs.getString("quantity");
                String price = rs.getString("price");
                String[] data = {cID,isbn,title,quan,price};
                model.addRow(data);
            }
            }catch(Exception e){}
        }
    }//GEN-LAST:event_viewCartActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(home);
        parent.repaint();
        parent.revalidate();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Object source = evt.getSource();
        if (source == jButton2) {
            logIn a = new logIn();
            String applicantSSN = String.valueOf(a.getssn());
            try {
                String bookName = jTextField1.getText();
                String bookAuthor = jTextField2.getText();
                String suggestionDate = jTextField3.getText();
                String isbn = jTextField10.getText();

                if (!bookName.isEmpty() && !bookAuthor.isEmpty() && !suggestionDate.isEmpty()) {
                    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                    String user, url, password;
                    url = "jdbc:oracle:thin:@192.168.1.184:1521:XE";
                    user = "C##BOOKSTORE";
                    password = "scranton";
                    Connection con = DriverManager.getConnection(url, user, password);
                    con.setAutoCommit(false);
                    Statement smt = con.createStatement();
                    String sql = "insert into suggestions(ssn,title,author,s_date,isbn) VALUES('"+applicantSSN+"','"+bookName+"','"+bookAuthor+"','"+suggestionDate+"','"+isbn+"')";
//                    PreparedStatement ps = con.prepareStatement(sql);
//                    ps.setString(1, applicantSSN);
//                    ps.setString(2, bookName);
//                    ps.setString(3, bookAuthor);
//                    ps.setString(4, suggestionDate);
//                    ps.setString(5, isbn);

                    int b = smt.executeUpdate(sql);
                    if (b > 0) {
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jTextField3.setText("");
                        jTextField10.setText("");
                        JOptionPane.showMessageDialog(null, "Suggestion sent successfully.");
                    }
                    con.commit();
                    con.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Kindly fill all the fields.");
                }

            } catch (SQLException ex) {
                Logger.getLogger(VCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Object source = evt.getSource();
        if (source == jButton4) {
            logIn a = new logIn();
            int customerSSN = a.getssn();
            try {
                String phone = jTextField4.getText();
                String city = jTextField5.getText();
                String email = jTextField6.getText();
                String userName = jTextField7.getText();
                String Password = jTextField8.getText();

                if (!phone.isEmpty() && !city.isEmpty() && !email.isEmpty() && !userName.isEmpty() && !Password.isEmpty()) {
                    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                    String user, url, password;
                    url = "jdbc:oracle:thin:@192.168.1.184:1521:XE";
                    user = "C##BOOKSTORE";
                    password = "scranton";
                    Connection con = DriverManager.getConnection(url, user, password);
                    con.setAutoCommit(false);
                    String sql = "update customers set city = '" + city + "', email = '" + email + "', phone = " + phone + " where ssn = " + customerSSN + "";
                    Statement smt = con.createStatement();
                    int c = smt.executeUpdate(sql);
                    String sql2 = "update accounts set password = '" +password+"',username = '"+userName+"' where ssn = '"+ customerSSN+"'";
                    Statement smt2 = con.createStatement();
                    smt2.executeUpdate(sql2);
                    if (c > 0) {
                        jTextField4.setText("");
                        jTextField5.setText("");
                        jTextField6.setText("");
                        jTextField7.setText("");
                        jTextField8.setText("");
                        JOptionPane.showMessageDialog(null, "Record updated successfully..");
                    }
                    con.commit();
                    con.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Fill out all the fields.");
                }

            } catch (SQLException ex) {
                Logger.getLogger(VCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object source = evt.getSource();
        if (source == jButton1) {
            dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new logIn().setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DisplayBook d = new DisplayBook();
        ArrayList<DisplayBook> data;
        if(evt.getClickCount()==2)
        {
            int i = jTable1.getSelectedRow();
            TableModel model = jTable1.getModel();
            //tableImg = (ImageIcon) model.getValueAt(i,0);
            tableISBN = model.getValueAt(i,0).toString();
            tableTitle =  model.getValueAt(i,1).toString();
            tableAuthor =  model.getValueAt(i,2).toString();
            
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayBook().setVisible(true);
                
            }
            
        });
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void contactus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactus2ActionPerformed
        // TODO add your handling code here:
        parent.removeAll();
        parent.add(conntactUs);
        parent.repaint();
        parent.revalidate();
    }//GEN-LAST:event_contactus2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton5)
        {
            try
            {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            int i = jTable2.getSelectedRow();
            String deleteItem = model.getValueAt(i,1).toString();
            System.out.println(deleteItem);
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String user,url,Password;
            url="jdbc:oracle:thin:@192.168.1.184:1521:XE";
            user="C##BOOKSTORE";
            Password="scranton";
            Connection con = DriverManager.getConnection(url,user,Password);
            con.setAutoCommit(false);
            String sql = "delete from items_cus where isbn =?";
           PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1,deleteItem);
            int a = ps.executeUpdate();
            if(a>0)
            {
                JOptionPane.showMessageDialog(null, "Item deleted.");
            }
            model.removeRow(jTable2.getSelectedRow());
            con.commit();
            con.close();
            }catch(Exception e){}
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==jButton6)
        {
            try {
                  DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                  Object[][] data = new Object[model.getRowCount()][model.getColumnCount()];
                  for(int i=0;i<model.getRowCount();i++)
                  {
                      for(int j = 0;j<model.getColumnCount();j++)
                      {
                           data[i][j] = model.getValueAt(i,j).toString();
                      }
                  }
                 
                     
                 String mgrCID = null;
                 String mgrISBN = null;
                 String mgrTitle = null;
                 String mgrQuan = null;
                 String mgrPrice = null;
                 int b = 0, totalAmount = 0;
                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String user, url, Password;
                url = "jdbc:oracle:thin:@192.168.1.184:1521:XE";
                user = "C##BOOKSTORE";
                Password = "scranton";
                System.out.println("1L");
                Connection con = DriverManager.getConnection(url, user, Password);
                con.setAutoCommit(false);
                ResultSet res; 
                        Statement st = con.createStatement();
                        res = st.executeQuery(
                    "SELECT COUNT(*) as NumberOfRows FROM "
                    + "Carts");
                        res.next();
                       int count = res.getInt("NumberOfRows");
                        System.out.println(count);
                        count++;
                String sqlc  ="insert into carts(c_id,ssn) values("+count+",'"+data[0][0]+"')";  
                System.out.println("2L");
                PreparedStatement psc = con.prepareStatement(sqlc);
                        psc.executeUpdate();
                        System.out.println("3L");
                
                for(int i=0;i<model.getRowCount();i++)
                  {
                      for(int j = 0;j<1;j++)
                      {
                          mgrCID = (String) data[i][j];
                          System.out.println(mgrCID);
                          mgrISBN = (String) data[i][j+1];
                          System.out.println(mgrISBN);
                          mgrTitle = (String) data[i][j+2];
                          System.out.println(mgrTitle);
                          mgrQuan = (String) data[i][j+3];
                          System.out.println(mgrQuan);
                          mgrPrice = (String) data[i][j+4];
                          System.out.println(mgrPrice);
                          totalAmount = totalAmount+Integer.parseInt(mgrPrice);
                         String sql1  ="insert into items(c_id,isbn,quantity) values("+count+",'"+mgrISBN+"',"+mgrQuan+")";   
                        
                        PreparedStatement ps = con.prepareStatement(sql1);
                        b = ps.executeUpdate();
                        System.out.println("3L");
                      }
                  }
                    if(b>0)
                    {
                        DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
    dm.removeRow(i);
}
                        
                        String sql2 = "delete from items_cus where c_id =?";
           PreparedStatement ps1 = con.prepareStatement(sql2);
            
            ps1.setString(1,mgrCID);
            ps1.executeUpdate();
            ps1 = con.prepareStatement("update carts set t_price=" + totalAmount+" where c_id="+count);
            ps1.executeUpdate();
                     JOptionPane.showMessageDialog(null,"Total Bill: "+totalAmount+
                             "\n"+"Your order has been placed successfully.");
                    }
            con.commit();
            con.close();
             }
             catch(Exception e)
             {
                 
             }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logIn().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel conntactUs;
    private javax.swing.JButton contactus2;
    private javax.swing.JPanel edit;
    private javax.swing.JButton edit1;
    private javax.swing.JPanel home;
    private javax.swing.JButton home1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel parent;
    private javax.swing.JPanel shop;
    private javax.swing.JButton shop1;
    private javax.swing.JPanel suggest;
    private javax.swing.JButton suggest1;
    private javax.swing.JButton viewCart;
    private javax.swing.JPanel viewCart1;
    // End of variables declaration//GEN-END:variables
}
